### ISSUE TITLE
Mixlib::ShellOut::ShellCommandFailed

### ISSUE THREAD

**Issue by ruffsl** [rhass/ros#9]
While running `knife cookbook site install ros` to install the cookbook, I encounter two warnings and an error that prevented successful installation. I am still new to Chef, and am not sure if this due to my system or a dependency issue with the ros cookbook

``` terminal
$ knife cookbook site install ros
Installing ros to /home/ubuntu/.chef/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-ros) exists, switching to it.
Downloading ros from Supermarket at version 0.3.0 to /home/ubuntu/.chef/cookbooks/ros.tar.gz
Cookbook saved: /home/ubuntu/.chef/cookbooks/ros.tar.gz
Removing pre-existing version.
Uncompressing ros version 0.3.0.
Removing downloaded tarball
No changes made to ros
Checking out the master branch.
Installing apt to /home/ubuntu/.chef/cookbooks
Checking out the master branch.
...
No changes made to supervisor
Checking out the master branch.
Installing python to /home/ubuntu/.chef/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-python) exists, switching to it.
WARNING: DEPRECATION: This cookbook has been deprecated. It has been replaced by poise-python.
WARNING: Use --force to force download deprecated cookbook.
Removing pre-existing version.
Uncompressing python version 1.4.6.
ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of tar zxvf "/home/ubuntu/.chef/cookbooks/python.tar.gz" ----
STDOUT: 
STDERR: tar (child): /home/ubuntu/.chef/cookbooks/python.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
---- End output of tar zxvf "/home/ubuntu/.chef/cookbooks/python.tar.gz" ----
Ran tar zxvf "/home/ubuntu/.chef/cookbooks/python.tar.gz" returned 2
```

**Comment by rhass** [comment]
This sounds like there was an issue with installing the the upstream python cookbook we depend on when using `site install`. You may want to consider just using [Berkshelf](http://berkshelf.com/) to resolve and mange dependencies. This cookbook is designed as a library cookbook, so you will need to have it as a dependency of whatever cookbook you create anyway.

The `ros_test` cookbook which I use as an integration test cookbook is a rough example of how this can be done, however it should be noted that the `ros_test` cookbook is missing a Berksfile (which might be a bug in my test cookbook). https://github.com/rhass/ros/tree/master/test/cookbooks/ros_test

**Comment by ruffsl** [comment]
Ok, looks like it installed nicely using Berkshelf from the chefdk v0.12.0-1 by editing the `Berksfile` and `metadata.rd` files appropriately. Once I edit, say the default.rb file in `myapp/recipes` directory (created from using `berks cookbook myapp`) to include the ros setup, is there a simple way of running the recipe locally with Berkshelf? It looks like it just manages dependencies, and chef-client is still doesn't know where to look. Previously I think I changed a knife config to include the path to the cookbook repo folders in `~/.chef`, but I'm not sure how to use Berkshelf with this.

``` terminal
~/Downloads/lol/myapp$ chef-client --local-mode recipes/default.rb 
[2016-04-04T14:28:26-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.8.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Installing Cookbook Gems:
Compiling Cookbooks...

Running handlers:
[2016-04-04T14:28:27-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-04-04T14:28:27-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 00 seconds
[2016-04-04T14:28:27-04:00] FATAL: Stacktrace dumped to /home/ruffsl/.chef/local-mode-cache/cache/chef-stacktrace.out
[2016-04-04T14:28:27-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-04-04T14:28:27-04:00] ERROR: No resource or method named `ros' for `Chef::Recipe "/home/ruffsl/Downloads/lol/myapp/recipes/default.rb"'
[2016-04-04T14:28:28-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by rhass** [comment]
There are a few ways you can go about this. 

1) Use [Test Kitchen](https://docs.chef.io/kitchen.html) to create and iterate within a local (pr cloud provider) virtual machine. This is nice because it makes testing and validating changes very easy and fairly quick. 

The other options are somewhat dependent on your deployment model.

2) If you use a hosted chef or a chef server, you can use `berks upload --no-freeze` to push your cookbook and all the dependencies to the chef server, and assuming your use(d) `knife bootstrap` to provision chef to your target system, chef-client should resolve everything just fine.

3) If you intend to use chef-solo or local-mode (zero), then you can use `berks package` to generate a tarball of your cookbook, and all the dependent cookbooks to upload to the target system, then extract and run chef against those cookbooks.

Let me know if you have any questions about any of these approaches, I am happy to help wherever I can. :smile:

**Comment by ruffsl** [comment]
I tried the 3rd method, as that just my intended use for now (using chef to bootstrap a fresh install anytime I hose or change/upgrade my local PC workstation). So I ran `berks package` in my `myapp` directory, then moved and extracted the tar.gz to a new directory and ran the `chef-client --local-mode` command from inside the extracted cookbook folder as well as the myapp folder, same results as above. I thought I remembered from a tutorial that chef automatically looks at the parent directory of the pwd for other cookbooks, but perhaps I'm mistaken. Looks like all the cookbooks are there in the generated package.

```
~/Downloads/cookbooks$ tree -L 1
.
├── apt
├── apt-repo
├── atom
├── build-essential
├── chef_handler
├── compat_resource
├── docker
├── homebrew
├── locale
├── myapp
├── packagecloud
├── poise
├── python
├── ros
├── seven_zip
├── supervisor
├── windows
├── yum
└── yum-epel
```

**Comment by rhass** [comment]
You may want to try creating a `client.rb` file and setting `cookbook_path` -- you can then just add `-c client.rb` to the options and it should pick up the correct path.

**Comment by ruffsl** [comment]
I assume you are referring to setting the config for [solo.rb](https://docs.chef.io/config_rb_solo.html#solo-rb) used by [local-mode](https://docs.chef.io/ctl_chef_client.html#run-in-local-mode)? I created a client.rb file setting the cookbook_path variable, but to no avail, same error as before.

```
~/Downloads/cookbooks$ echo "cookbook_path = \"/home/ruffsl/Downloads/cookbooks\"" > myapp/recipes/client.rb
~/Downloads/cookbooks$ chef-client --local-mode -c myapp/recipes/client.rb myapp/recipes/default.rb
```

**Comment by rhass** [comment]
If you can wait, I can give this a shot over the weekend. Otherwise, you may want to check out the chef forums at https://discourse.chef.io as this sounds mostly like an issue with running in local-mode. I will note, local-mode (also called chef-zero) and solo are two different things -- solo will likely turn into local-mode but I believe in the current versions of Chef they operate differently.

**Comment by ruffsl** [comment]
@rhass , I tried to make a docker file you could test with, 
but I'm not sure about the `Object not found: chefzero` error:
https://gist.github.com/ruffsl/f1abb7809a32bc54f2b4eabc9a629f58

**Comment by rhass** [comment]
@ruffsl I made comments in the gist.

**Comment by rhass** [comment]
I am closing this issue for now, but feel free to contact me directly or open an new issue.
